import { requiredScopes, type StravaScope } from './strava-scopes'

export interface StravaAuthConfig {
  readonly clientId: string
  readonly redirectUri: string
  readonly authorizationEndpoint: string
  readonly scopes: readonly StravaScope[]
  readonly stateGenerator: () => string
}

export const stravaAuthorizationEndpoint = 'https://www.strava.com/oauth/authorize'

/**
 * Where the OS hands the authorization response back to the app, after the
 * https bridge redirects to it. Never sent to Strava — Strava only accepts a
 * bare callback domain, so the redirect_uri is the bridge URL instead.
 *
 * Must match the `scheme` in apps/mobile/app.json.
 */
export const stravaAppCallbackUri = 'gradnt://strava/callback'

/**
 * Builds the Strava authorization URL for the OAuth redirect flow.
 *
 * Pure and deterministic: no network, no secrets, no token exchange.
 * The state parameter is generated by the injected generator so the
 * callback can later validate the response against the requested flow.
 */
export function buildAuthorizationUrl(config: StravaAuthConfig): string {
  const url = new URL(config.authorizationEndpoint)
  url.searchParams.set('response_type', 'code')
  url.searchParams.set('client_id', config.clientId)
  url.searchParams.set('redirect_uri', config.redirectUri)
  url.searchParams.set('scope', config.scopes.join(' '))
  url.searchParams.set('state', config.stateGenerator())

  return url.toString()
}

/**
 * Reads the Strava wiring from the environment, or returns null when the
 * application has not been configured yet. Callers surface that as
 * `not_configured` rather than crashing on a missing client id.
 *
 * One URL serves both roles: the endpoint answers the OAuth redirect over GET
 * (bridging to the app scheme) and the token exchange over POST. So it is also
 * the `redirect_uri` sent to Strava, which is why the Strava callback domain
 * must cover the host it lives on.
 */
export interface StravaRuntimeConfig {
  auth: Omit<StravaAuthConfig, 'stateGenerator'>
  endpointUrl: string
}

export function readStravaConfig(): StravaRuntimeConfig | null {
  const clientId = process.env.EXPO_PUBLIC_STRAVA_CLIENT_ID?.trim()
  const endpointUrl = process.env.EXPO_PUBLIC_STRAVA_ENDPOINT_URL?.trim()

  if (!clientId || !endpointUrl) {
    return null
  }

  return {
    auth: {
      clientId,
      redirectUri: endpointUrl,
      authorizationEndpoint: stravaAuthorizationEndpoint,
      scopes: requiredScopes,
    },
    endpointUrl,
  }
}

/**
 * URL of the refresh function.
 *
 * Derived from the exchange URL rather than configured separately: the two are
 * siblings in the same deployment, and a second variable that has to agree with
 * the first is one more way to misconfigure the app.
 *
 * Returns null when the URL does not have the shape we expect, so the caller
 * reports a configuration problem instead of posting a refresh to the exchange
 * endpoint and silently getting nothing back.
 */
export function readStravaRefreshUrl(): string | null {
  const config = readStravaConfig()

  if (config === null) {
    return null
  }

  const match = /^(.*\/)strava-exchange\/?$/.exec(config.endpointUrl)

  return match ? `${match[1]}strava-refresh` : null
}
