import type { StravaScope } from './strava-scopes'

export interface StravaAuthConfig {
  readonly clientId: string
  readonly redirectUri: string
  readonly authorizationEndpoint: string
  readonly scopes: readonly StravaScope[]
  readonly stateGenerator: () => string
}

/**
 * Builds the Strava authorization URL for the OAuth redirect flow.
 *
 * Pure and deterministic: no network, no secrets, no token exchange.
 * The state parameter is generated by the injected generator so the
 * callback can later validate the response against the requested flow.
 */
export function buildAuthorizationUrl(config: StravaAuthConfig): string {
  const url = new URL(config.authorizationEndpoint)
  url.searchParams.set('response_type', 'code')
  url.searchParams.set('client_id', config.clientId)
  url.searchParams.set('redirect_uri', config.redirectUri)
  url.searchParams.set('scope', config.scopes.join(' '))
  url.searchParams.set('state', config.stateGenerator())

  return url.toString()
}
